hw1 todo.sql
alekceev/gb-pg pull request #2
Opened 2021-07-06 10:46 UTC by alekceev

2021-07-08 21:47 UTC, heerakli requested changes
А где остальная часть? я про пункты 6-8 из задания?

2021-07-08 21:47 UTC, heerakli commented on docker-compose.yml
> +      - "127.0.0.1:5431:15434"
в этом случае надо указать этот порт в переменной окружения POSTGRES_PORT: 15434, иначе будет прокинут порт на котором ничего не работает.

2021-07-08 21:47 UTC, heerakli commented on todo.sql
> +    uuid uuid not null default uuid_generate_v4() primary key,
Это очень хорошо, что вы знаете как подключить экстеншен и использовать специальные типы и функции из него, но насколько это оправдано? Мне кажется польза uuid в том, что он может быть сгенерирован в приложении.

2021-07-15 03:12 UTC, alekceev commented on todo.sql
> +    uuid uuid not null default uuid_generate_v4() primary key,
Согласен, можно использовать поле varchar нужной длины и логику генерации переложить на приложение, если не нужно использовать генерацию uuid в тригеррах или каких либо функциях. UUID, вместо числового типа выбран, не случайно. Связано это с точки зрения атак на id методом перебора, точно не помню как такие атаки называют. На самом деле я подробнее хотел узнать о плюсах и минусах использования такого идентификатора с точки зрения производительности и использования.

2021-07-15 03:13 UTC, alekceev commented on docker-compose.yml
> +      - "127.0.0.1:5431:15434"
Да, я это заметил позже, когда попытался подключится на проброшенный порт. Исправленно в другом мержреквесте

2021-07-22 07:15 UTC, merged